[package]
name = "librim"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37.0", features = ["full"] }
ffmpeg-next = { version = "7.0.0", features = ["build"] }
base64 = { version = "0.22.0" }
md-5 = { version = "0.10.6" }
image = { version = "0.25.1" }

[lib]
name = "librim"
path = "src/lib.rs"
