[package]
name = "librim"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37.0", features = ["full"] }
tokio-stream = "0.1.15"
md-5 = "0.10.6"
image = "0.25.1"
base64 = "0.22.0"

[lib]
name = "librim"
path = "src/lib.rs"
