[package]
name = "rim-cli"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
toml = { version = "0.8.12" }
librim = { path = "../rim" }

[[bin]]
name = "rim"
path = "src/cli.rs"