[package]
name = "rim-cli"
version = "0.1.2"
edition = "2021"

[dependencies]
librim = { path = "../rim" }
clap = { version= "4.5.4", features=["derive"] }
toml = { version = "0.8.12"}

[[bin]]
name = "rim"
path = "src/cli.rs"
