[package]
name = "rim-cli"
version = "0.3.10"
edition = "2021"

[dependencies]
clap = { version = "4.5.6", features = ["derive"] }
librim = { path = "../rim" }

[[bin]]
name = "rim"
path = "src/cli.rs"