name: ci

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rui314/setup-mold@v1
      - run: sudo apt-get -qq update && sudo apt-get -qq install pkg-config yasm nasm musl-dev clang llvm
      - run: curl -fsSL https://sh.rustup.rs | sh -s -- -y
      - run: . "$HOME/.cargo/env"
      - run: rustup update nightly && rustup default nightly
      - run: cargo build --release